# Generated by Django 4.0.5 on 2022-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_logger', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('SP', 'Sports'), ('FD', 'Food & Drink'), ('WK', 'Work'), ('PR', 'Personal'), ('ST', 'Study'), ('VT', 'Visit'), ('OT', 'Other')], default='OT', max_length=20, null=True),
        ),
    ]
